### ISSUE TITLE
Error 404 at 2am (no metro)

### ISSUE THREAD

**Issue by mukel** [RemembrMoe/tl-api#1]
I wrote a tiny Scala wrapper for your API, way better than scrapping the TL site by hand.
I'm trying to use your API to query the EPFL metro M1 horaires. The horaires seems broken at 2am (no metro until 5am). The TL site also doesn't show anything for 2AM queries.
I'd like to get the next metro, or an empty answer instead of an error.
Any hint?

**Comment by dgellow** [comment]
Hello @mukel. Glad to know someone is using this API :)

About your issue, that's something you have to manage on your client. You can check the value returned from the API and treat it as empty if you get a 404.
